### ISSUE TITLE
Installing Node.js Failed

### ISSUE THREAD

**Issue by thsowers** [c9s/typeloy#16]
When running the setup or deploy commands I'm receiving the error:

`[xxx.xxx.xx.xx] x Installing Node.js: undefined: FAILED
    ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typeloy/scripts/linux/install-node.sh'
`

and 

`[xxx.xxx.xx.xx] - Setting up environment variables
[xxx.xxx.xx.xx] x Setting up environment variables: FAILED
    ENOENT: no such file or directory, open '/usr/local/lib/node_modules/typeloy/templates/linux/env.sh'
`

**Comment by c9s** [comment]
Uploaded a patch release, please take a look.

typeloy 1.1.3

**Comment by thsowers** [comment]
Looks all set! :D
