### ISSUE TITLE
Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by thsowers** [c9s/typeloy#18]
When running deploy, I get this error

`Waiting for MongoDB to initialize. (5 minutes)
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    connected
`

Edit: Could be possibly related to #19?

**Comment by c9s** [comment]
I'm not sure. could you provide the trace stack? basically the behaviour is the same as mup right now.

I think you need "wait-for-mongo" and make sure the mongo driver is supported.

**Comment by c9s** [comment]
so in your issue #19, it hangs because it's waiting for mongo connection.

**Comment by thsowers** [comment]
Here's the full trace stack:

`+ wait-for-mongo 'mongodb://xx.xxx.xx:27017,xxx.xxx.xxx.xx:27017/GEM?replicaSet=GEM&ssl=true' 300000
    bash: line 153: wait-for-mongo: command not found
    -----------------------------------STDOUT-----------------------------------
    ypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      COPY Release/bcrypt_lib.node
    make: Leaving directory`/opt/GEM/tmp/bundle/programs/server/node_modules/bcrypt/build'
    ansi-regex@0.2.1 node_modules/ansi-regex

```
ansi-styles@1.1.0 node_modules/ansi-styles

escape-string-regexp@1.0.5 node_modules/escape-string-regexp

chalk@0.5.1 node_modules/chalk

amdefine@1.0.0 node_modules/amdefine

has-ansi@0.1.0 node_modules/has-ansi

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

meteor-promise@0.7.2 node_modules/meteor-promise

asap@2.0.4 node_modules/asap

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

source-map@0.1.32 node_modules/source-map

promise@7.1.1 node_modules/promise

fibers@1.0.13 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
----------------------------------------------------------------------------
```

`

**Comment by thsowers** [comment]
I've tried installing mongo-connector on the server but the error persists. I was able to get `muprockanew` running to satisfy my immediate need to get code onto the server for the time being. Looks like this issue is related to new the `mup` version

**Comment by c9s** [comment]
you need `wait-for-mongo`, which can be installed by:

```
npm install -g wait-for-mongo
```

this should be already done in f2f9ba80

**Comment by c9s** [comment]
btw, I think the original mup build script needs to be fix, it doesn't install the node gyp modules correctly.

**Comment by c9s** [comment]
should be fixed.
