### ISSUE TITLE
SSL support and maintaining

### ISSUE THREAD

**Issue by Twisterking** [c9s/typeloy#21]
Hello c9s!

First of all: Thank you for all the effort you already put into this fork of `mup` - which is more like its own project!
I found your post [here](https://github.com/meteor/meteor/issues/7475) and immediately loved it!

I've got two questions:
- Does the SSL support work properly? Do the same `.pem` files work as used by the `mupx` branch?
- are you planing on maintaining this project? I depend on this project very much!

Thank you in advance, best P

**Comment by c9s** [comment]
@Twisterking 

Typeloy was forked from master (which is mup) so it has the same behaviour with mup (but not mupx)

You can describe your setup here and I can see how to support things like this.

**Comment by c9s** [comment]
@Twisterking Yes the same pem still work, and we're going to support certbot! stay tuned !
