### ISSUE TITLE
Meteor 1.4

### ISSUE THREAD

**Issue by rootedsoftware** [c9s/typeloy#22]
Does Typeloy support node version 4.4.7 with Meteor 1.4? All the examples reference node versions for previous Meteor releases.

Thanks

**Comment by c9s** [comment]
Will work on it soon. After meteor 1.4 getting stable enough.

**Comment by c9s** [comment]
Progressing

**Comment by Testato** [comment]
@c316 
Yes, by today typeloy-master improvement I installed Node 4.6.0 used by the last Meteor 1.4.1.2
You can close this Issues

**Comment by rootedsoftware** [comment]
Thanks
