### ISSUE TITLE
Warning minimatch

### ISSUE THREAD

**Issue by Testato** [c9s/typeloy#33]
npm WARNING
`deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Comment by Testato** [comment]
Vulnerability report for typeloy
https://snyk.io/test/npm/typeloy

**Comment by c9s** [comment]
looks like this can be fixed by upgrading archive

Testato notifications@github.com 於 2016年10月8日 星期六寫道：

**Comment by c9s** [comment]
Fixed.
