### ISSUE TITLE
Setup systemd for Mongo

### ISSUE THREAD

**Issue by c9s** [c9s/typeloy#36]
Mongodb on Ubuntu 16.04 doesn't have systemctl service entry, we need to create one manually.

**Comment by Testato** [comment]
I have one

**Comment by Testato** [comment]
[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target

[Service]
User=mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

[Install]
WantedBy=multi-user.target

**Comment by c9s** [comment]
This one should be done.
