### ISSUE TITLE
Server Reboot daemons

### ISSUE THREAD

**Issue by Testato** [c9s/typeloy#49]
after a server reboot the Mongo service do not autostart.

```
sudo service mongo status
● mongo.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/lib/systemd/system/mongo.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://docs.mongodb.org/manual
```

**Comment by c9s** [comment]
because your "mongod.service" was not removed?

Testato notifications@github.com 於 2016年10月13日 星期四寫道：

**Comment by Testato** [comment]
no, it is removed, 
probably you need only `Restart=always` in the mongo service
the systemD daemon need this for two reason:
1) autostart at reboot
2) auto restart after a crash

**Comment by c9s** [comment]
Restart=aways is for process level, not for reboot.

maybe you can try systemctl enable mongo ?

Testato notifications@github.com 於 2016年10月13日 星期四寫道：

**Comment by Testato** [comment]
sorry, yes, you are right `Restart=always` if only for respawn after a crash
I seen that you applied it to the meteorapp.service, why not add it also on mongo.service ? so also mongodb will restart after a crash

**Comment by Testato** [comment]
Solved 
Thanks
